DROP DATABASE IF EXISTS wallet;
CREATE DATABASE wallet CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP USER IF EXISTS 'lreader'@'127.0.0.1';
CREATE USER lreader@'127.0.0.1' IDENTIFIED BY 'secret';
GRANT SELECT, INSERT, UPDATE ON wallet.* TO 'lreader'@'127.0.0.1';
FLUSH PRIVILEGES;

USE wallet;

DROP TABLE IF EXISTS LOG_REGISTRATION;
CREATE TABLE LOG_REGISTRATION (
  ID_LOG int NOT NULL AUTO_INCREMENT,
  REQ_TM DATETIME NOT NULL,
  IP_ADDR varchar(15) NOT NULL,
  REQ_TYPE varchar(30) NOT NULL,
  RESP_CODE varchar(3) NOT NULL,
  USER_AGENT varchar(250) NOT NULL,
  PRIMARY KEY (ID_LOG)
)ENGINE=InnoDB;

ALTER TABLE LOG_REGISTRATION ADD INDEX logRequest (REQ_TM);

DROP TABLE IF EXISTS LOG_RESULTS;
CREATE TABLE LOG_RESULTS (
  ID_RESULT int NOT NULL AUTO_INCREMENT,
  IP_ADDR varchar(15) NOT NULL,
  IP_CNT INTEGER NOT NULL,
  RSLT_REASON varchar(250),
  PRIMARY KEY (ID_RESULT)
)ENGINE=InnoDB;
